version: "3.9"

services:
  database:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: application
      POSTGRES_USER: application
      POSTGRES_DB: application
      TZ: America/Sao_Paulo
    volumes:
      - application_data:/var/lib/postgresql/data

  seed:
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file:
      - .env
    environment:
      DB_HOST: database
    command: "npm run seed"
    depends_on:
      - database
  
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    environment:
      DB_HOST: database
    ports:
      - 3000:3000
    depends_on:
      - database
      - seed

volumes:
  application_data: